kind: pipeline
type: docker
name: symfony-deploy

steps:
  - name: quality
    image: jakzal/phpqa:php8.3-alpine
    commands:
      - composer validate
      - parallel-lint . --exclude vendor


  - name: build
    image: jakzal/phpqa:php8.3-alpine
    commands:
      - composer install --optimize-autoloader --ignore-platform-reqs
      - composer dump-autoload --classmap-authoritative
    depends_on:
      - quality

  - name: deploy-staging
    image: alpine:3
    commands:
      - apk update && apk upgrade
      - apk add openssh bash rsync
      - mkdir -p ~/.ssh
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
      - printf "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null\n" > ~/.ssh/config
      - chmod 600 ~/.ssh/id_ed25519
      - eval $(ssh-agent -s)
      - ssh-add ~/.ssh/id_ed25519
      - rsync -rav --quiet --delete -e "ssh -p $STAGING_SSH_PORT" --exclude='.env.local' --exclude='config/jwt' --exclude='var' ./ $STAGING_SSH_USER@$STAGING_SSH_HOST:$STAGING_PATH/
      - ssh -p $STAGING_SSH_PORT $STAGING_SSH_USER@$STAGING_SSH_HOST "cd $STAGING_PATH && bin/console cache:clear"
    environment:
      SSH_PRIVATE_KEY:
        from_secret: staging_ssh_key
      STAGING_SSH_PORT:
        from_secret: staging_ssh_port
      STAGING_SSH_HOST:
        from_secret: staging_ssh_host
      STAGING_SSH_USER:
        from_secret: staging_ssh_user
      STAGING_PATH:
        from_secret: staging_path
    depends_on:
      - build
    when:
      branch:
        - dev

  - name: deploy-production
    image: alpine:3
    commands:
      - apk update && apk upgrade
      - apk add openssh bash rsync
      - mkdir -p ~/.ssh
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
      - printf "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null\n" > ~/.ssh/config
      - chmod 600 ~/.ssh/id_ed25519
      - eval $(ssh-agent -s)
      - ssh-add ~/.ssh/id_ed25519
      - rsync -rav --quiet --delete -e "ssh -p $PRODUCTION_SSH_PORT" --exclude='.env.local' --exclude='config/jwt' --exclude='var' ./ $PRODUCTION_SSH_USER@$PRODUCTION_SSH_HOST:$PRODUCTION_PATH/
      - ssh -p $PRODUCTION_SSH_PORT $PRODUCTION_SSH_USER@$PRODUCTION_SSH_HOST "cd $PRODUCTION_PATH && bin/console cache:clear"
    environment:
      SSH_PRIVATE_KEY:
        from_secret: production_ssh_key
      PRODUCTION_SSH_PORT:
        from_secret: production_ssh_port
      PRODUCTION_SSH_HOST:
        from_secret: production_ssh_host
      PRODUCTION_SSH_USER:
        from_secret: production_ssh_user
      PRODUCTION_PATH:
        from_secret: production_path
    depends_on:
      - build
    when:
      branch:
        - main

trigger:
  branch:
    - dev
    - main
